[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]
path ="src/main.rs"
name ="auth_basic_jwt"


[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
app = { path = "app"}
dotenv = "0.15.0"
