version: "3"

services:
  app:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    environment:
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
      - DATABASE_URL=postgres://username:password@database/auth_basic_jwt_db
    depends_on:
      database:
        condition: service_healthy
  

  database:
    image: postgres:16-alpine
    shm_size: 100mb
    restart: always
    volumes:
      - auth_basic_jwt_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth_basic_jwt_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  auth_basic_jwt_volume:


